### ISSUE TITLE
Unable to compile with nginx 1.2.1 (Debian Wheezy package)

### ISSUE THREAD

**Issue by Napsty** [nbs-system/naxsi#316]
Tried to create new Debian Wheezy packages based on the Debian source packages with nginx 1.2.1 with the latest master from today. 
But it fails:

	objs/addon/naxsi_src/naxsi_skeleton.o:/root/src/nginx-1.2.1/debian/modules/naxsi/naxsi_src/naxsi_skeleton.c:164: first defined here
	objs/addon/naxsi_src/naxsi_skeleton.o:(.data+0x0): multiple definition of `ngx_http_naxsi_module'
	objs/addon/naxsi_src/naxsi_skeleton.o:(.data+0x0): first defined here
	objs/src/http/modules/ngx_http_autoindex_module.o: In function `memset':
	/usr/include/x86_64-linux-gnu/bits/string3.h:82: warning: memset used with constant zero length parameter; this could be due to transposed parameters
	objs/addon/naxsi_src/naxsi_raw.o: In function `ngx_http_dummy_rawbody_parse':
	/root/src/nginx-1.2.1/debian/build-naxsi/../../../naxsi-master/naxsi_src//naxsi_raw.c:56: undefined reference to `naxsi_unescape'
	collect2: error: ld returned 1 exit status
	make[2]: *** [objs/nginx] Error 1
	make[2]: Leaving directory `/root/src/nginx-1.2.1/debian/build-naxsi'
	make[1]: *** [build] Error 2
	make[1]: Leaving directory `/root/src/nginx-1.2.1/debian/build-naxsi'
	make: *** [build-arch.naxsi] Error 2
	dpkg-buildpackage: error: debian/rules build gave error exit status 2

In debian/rules file the naxsi module was added as first module right after --conf-path:

	config.status.naxsi: config.env.naxsi config.sub config.guess
		cd $(BUILDDIR_naxsi) && CFLAGS="$(CFLAGS)" CORE_LINK="$(LDFLAGS)" ./configure  \
		    --prefix=/etc/nginx \
		    --conf-path=/etc/nginx/nginx.conf \
		    --add-module=../../../naxsi-master/naxsi_src/ \
		    --error-log-path=/var/log/nginx/error.log \
		    --http-client-body-temp-path=/var/lib/nginx/body \
		    --http-fastcgi-temp-path=/var/lib/nginx/fastcgi \
		    --http-log-path=/var/log/nginx/access.log \
		    --http-proxy-temp-path=/var/lib/nginx/proxy \
		    --http-scgi-temp-path=/var/lib/nginx/scgi \
		    --http-uwsgi-temp-path=/var/lib/nginx/uwsgi \
		    --lock-path=/var/lock/nginx.lock \
		    --pid-path=/var/run/nginx.pid \
		    --with-pcre-jit \
		    --with-http_ssl_module \
		    --without-mail_pop3_module \
		    --without-mail_smtp_module \
		    --without-mail_imap_module \
		    --without-http_uwsgi_module \
		    --without-http_scgi_module \
		    --with-ipv6 \
		    --with-http_stub_status_module \
		    --add-module=$(MODULESDIR)/nginx-upstream-fair \
		    --add-module=$(MODULESDIR)/nginx-cache-purge \
		    --add-module=$(MODULESDIR)/naxsi/naxsi_src \
		    $(CONFIGURE_OPTS) >$@

**Comment by Napsty** [comment]
I feel stupid now... 
I forgot to remove the original --add-module for naxsi from the debian/rules at the bottom of the configure command (see above). All good, package was built.
